// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using arielramos_progreso1.Data;

#nullable disable

namespace arielramos_progreso1.Migrations
{
    [DbContext(typeof(arielramos_progreso1Context))]
    partial class arielramos_progreso1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("arielramos_progreso1.Models.ArielRamos_Tabla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("ArAlturaM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ArEmpleado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ArFechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArNombre")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<decimal>("ArPesoKilogramos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ArielRamos_Tabla");
                });
#pragma warning restore 612, 618
        }
    }
}
